-- ============================================================
-- Migración: Grupos de Gastos Compartidos
-- Fecha: 2026-05-07
-- Descripción: Crea el módulo completo de grupos compartidos.
--   - 6 tablas con índices
--   - 2 funciones helper SECURITY DEFINER (is_group_member, is_group_admin)
--   - 2 triggers (updated_at, auto-alta del creador como admin)
--   - RLS habilitado + políticas por tabla
--   - Vista vw_grupo_saldos
--   - RPC aceptar_invitacion_grupo
-- Ejecutar en Supabase SQL Editor de una sola vez.
-- ============================================================

BEGIN;

-- ============================================================
-- SECCIÓN 1: TABLAS E ÍNDICES
-- Orden respeta las FK: grupos_gastos primero, luego las hijas.
-- ============================================================

-- 1.1 grupos_gastos
-- Entidad raíz del módulo. Cada grupo tiene un creador y puede archivarse.
CREATE TABLE IF NOT EXISTS grupos_gastos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(120) NOT NULL,
    descripcion         TEXT,
    creado_por          UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    moneda              VARCHAR(8)  NOT NULL DEFAULT 'ARS',
    archivado           BOOLEAN     NOT NULL DEFAULT FALSE,
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- Índice para listar grupos por creador (admin dashboard)
CREATE INDEX idx_grupos_gastos_creado_por ON grupos_gastos(creado_por);

-- 1.2 grupo_miembros
-- Membresía de un usuario en un grupo. Soft delete via estado='removido'.
CREATE TABLE IF NOT EXISTS grupo_miembros (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id    BIGINT      NOT NULL REFERENCES grupos_gastos(id) ON DELETE CASCADE,
    user_id     UUID        NOT NULL REFERENCES auth.users(id)    ON DELETE CASCADE,
    rol         VARCHAR(20) NOT NULL DEFAULT 'miembro',
    -- Roles válidos: admin | miembro
    estado      VARCHAR(20) NOT NULL DEFAULT 'activo',
    -- Estados válidos: activo | removido
    alias       VARCHAR(80),
    fecha_alta  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_baja  TIMESTAMPTZ,
    CONSTRAINT grupo_miembros_unique     UNIQUE(grupo_id, user_id),
    CONSTRAINT grupo_miembros_rol_chk   CHECK (rol    IN ('admin','miembro')),
    CONSTRAINT grupo_miembros_estado_chk CHECK (estado IN ('activo','removido'))
);
CREATE INDEX idx_grupo_miembros_grupo       ON grupo_miembros(grupo_id);
CREATE INDEX idx_grupo_miembros_user        ON grupo_miembros(user_id);
-- Índice parcial: acelera búsquedas de miembros activos por usuario
CREATE INDEX idx_grupo_miembros_user_activo ON grupo_miembros(user_id) WHERE estado = 'activo';

-- 1.3 grupo_invitaciones
-- Invitaciones por email con token UUID generado por Supabase.
-- El backend Express solo hace INSERT y lee el token resultante.
CREATE TABLE IF NOT EXISTS grupo_invitaciones (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id          BIGINT      NOT NULL REFERENCES grupos_gastos(id) ON DELETE CASCADE,
    email_invitado    VARCHAR(255) NOT NULL,
    token             UUID        NOT NULL DEFAULT gen_random_uuid(),
    invitado_por      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    estado            VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    -- Estados válidos: pendiente | aceptada | rechazada | expirada | cancelada
    fecha_expiracion  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
    fecha_creacion    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_resolucion  TIMESTAMPTZ,
    CONSTRAINT grupo_invitaciones_token_unique  UNIQUE(token),
    CONSTRAINT grupo_invitaciones_estado_chk   CHECK (estado IN ('pendiente','aceptada','rechazada','expirada','cancelada'))
);
CREATE INDEX idx_grupo_invitaciones_grupo    ON grupo_invitaciones(grupo_id);
-- Índice en email en minúsculas para búsquedas case-insensitive
CREATE INDEX idx_grupo_invitaciones_email    ON grupo_invitaciones(LOWER(email_invitado));
-- Índice parcial: solo invitaciones pendientes (el caso de uso más frecuente)
CREATE INDEX idx_grupo_invitaciones_pendiente ON grupo_invitaciones(grupo_id, estado) WHERE estado = 'pendiente';

-- 1.4 grupo_gastos
-- Gasto cargado dentro de un grupo. Soft delete via estado='anulado'.
-- id_categoria es opcional y referencia las categorías personales/globales del módulo principal.
CREATE TABLE IF NOT EXISTS grupo_gastos (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id     BIGINT       NOT NULL REFERENCES grupos_gastos(id)  ON DELETE CASCADE,
    descripcion  TEXT         NOT NULL,
    monto        DECIMAL(12,2) NOT NULL CHECK (monto > 0),
    moneda       VARCHAR(8)   NOT NULL DEFAULT 'ARS',
    pagado_por   UUID         NOT NULL REFERENCES auth.users(id)     ON DELETE RESTRICT,
    fecha        DATE         NOT NULL DEFAULT CURRENT_DATE,
    nota         TEXT,
    -- Categoría opcional: solo informativa, no afecta saldos del grupo.
    -- Solo se permiten categorías globales (user_id IS NULL) en la UI (ver db.js).
    id_categoria BIGINT       REFERENCES categorias(id)              ON DELETE SET NULL,
    estado       VARCHAR(20)  NOT NULL DEFAULT 'activo',
    -- Estados válidos: activo | anulado
    creado_por   UUID         NOT NULL REFERENCES auth.users(id)     ON DELETE RESTRICT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    anulado_en   TIMESTAMPTZ,
    anulado_por  UUID         REFERENCES auth.users(id),
    CONSTRAINT grupo_gastos_estado_chk CHECK (estado IN ('activo','anulado'))
);
CREATE INDEX idx_grupo_gastos_grupo   ON grupo_gastos(grupo_id);
CREATE INDEX idx_grupo_gastos_pagador ON grupo_gastos(pagado_por);
-- Índice para listar gastos del grupo por fecha descendente
CREATE INDEX idx_grupo_gastos_fecha   ON grupo_gastos(grupo_id, fecha DESC);
-- Índice parcial: acelera la vista vw_grupo_saldos que filtra por estado='activo'
CREATE INDEX idx_grupo_gastos_activos ON grupo_gastos(grupo_id) WHERE estado = 'activo';

-- 1.5 grupo_gasto_participantes
-- Porción del gasto asignada a cada participante. monto_asignado se persiste
-- calculado al insertar para evitar recalcular siempre y permitir porcentajes
-- custom en el futuro.
CREATE TABLE IF NOT EXISTS grupo_gasto_participantes (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gasto_id        BIGINT       NOT NULL REFERENCES grupo_gastos(id) ON DELETE CASCADE,
    user_id         UUID         NOT NULL REFERENCES auth.users(id)   ON DELETE RESTRICT,
    -- Preparado para porcentajes futuros; en MVP siempre se calcula igualitariamente en db.js
    porcentaje      DECIMAL(7,4),
    monto_asignado  DECIMAL(12,2) NOT NULL CHECK (monto_asignado >= 0),
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT grupo_gasto_participantes_unique UNIQUE(gasto_id, user_id)
);
CREATE INDEX idx_grupo_gasto_participantes_gasto ON grupo_gasto_participantes(gasto_id);
CREATE INDEX idx_grupo_gasto_participantes_user  ON grupo_gasto_participantes(user_id);

-- 1.6 grupo_liquidaciones
-- Registra pagos directos entre miembros que reducen deudas. Soft delete via estado='anulada'.
CREATE TABLE IF NOT EXISTS grupo_liquidaciones (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id      BIGINT       NOT NULL REFERENCES grupos_gastos(id) ON DELETE CASCADE,
    de_user_id    UUID         NOT NULL REFERENCES auth.users(id)    ON DELETE RESTRICT,
    para_user_id  UUID         NOT NULL REFERENCES auth.users(id)    ON DELETE RESTRICT,
    monto         DECIMAL(12,2) NOT NULL CHECK (monto > 0),
    fecha         DATE         NOT NULL DEFAULT CURRENT_DATE,
    nota          TEXT,
    estado        VARCHAR(20)  NOT NULL DEFAULT 'confirmada',
    -- Estados válidos: confirmada | anulada
    registrado_por UUID        NOT NULL REFERENCES auth.users(id)    ON DELETE RESTRICT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    anulada_en    TIMESTAMPTZ,
    CONSTRAINT grupo_liquidaciones_distintos    CHECK (de_user_id <> para_user_id),
    CONSTRAINT grupo_liquidaciones_estado_chk  CHECK (estado IN ('confirmada','anulada'))
);
CREATE INDEX idx_grupo_liquidaciones_grupo ON grupo_liquidaciones(grupo_id);
CREATE INDEX idx_grupo_liquidaciones_de    ON grupo_liquidaciones(de_user_id);
CREATE INDEX idx_grupo_liquidaciones_para  ON grupo_liquidaciones(para_user_id);

-- ============================================================
-- SECCIÓN 2: FUNCIONES HELPER (SECURITY DEFINER STABLE)
-- Razón: policies inline con subqueries sobre grupo_miembros causan
-- recursión infinita cuando esa tabla tiene RLS. Con SECURITY DEFINER
-- los helpers bypassean RLS internamente y solo exponen BOOLEAN.
-- ============================================================

-- Verifica si un usuario es miembro activo de un grupo.
CREATE OR REPLACE FUNCTION is_group_member(p_grupo_id BIGINT, p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1 FROM grupo_miembros
        WHERE grupo_id = p_grupo_id
          AND user_id  = p_user_id
          AND estado   = 'activo'
    );
$$;

-- Verifica si un usuario es admin activo de un grupo.
CREATE OR REPLACE FUNCTION is_group_admin(p_grupo_id BIGINT, p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1 FROM grupo_miembros
        WHERE grupo_id = p_grupo_id
          AND user_id  = p_user_id
          AND estado   = 'activo'
          AND rol      = 'admin'
    );
$$;

-- Verifica si un usuario es el creador original del grupo.
CREATE OR REPLACE FUNCTION is_group_creator(p_grupo_id BIGINT, p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1 FROM grupos_gastos
        WHERE id = p_grupo_id
          AND creado_por = p_user_id
    );
$$;

-- Revocar acceso público y otorgar solo a usuarios autenticados.
-- Esto evita que el rol anon pueda invocar los helpers desde el cliente.
REVOKE ALL ON FUNCTION is_group_member(BIGINT, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION is_group_admin (BIGINT, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION is_group_creator(BIGINT, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION is_group_member(BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION is_group_admin (BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION is_group_creator(BIGINT, UUID) TO authenticated;

-- ============================================================
-- SECCIÓN 3: TRIGGERS
-- ============================================================

-- Trigger 3.1: Actualizar fecha_actualizacion en grupos_gastos al hacer UPDATE.
CREATE OR REPLACE FUNCTION grupos_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_grupos_gastos_updated_at
    BEFORE UPDATE ON grupos_gastos
    FOR EACH ROW EXECUTE FUNCTION grupos_set_updated_at();

-- Trigger 3.2: Al crear un grupo, insertar al creador como admin activo.
-- Garantía atómica: el creador siempre es miembro/admin desde la primera fila,
-- sin race condition con RLS.
CREATE OR REPLACE FUNCTION grupos_alta_admin_creador()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO grupo_miembros (grupo_id, user_id, rol, estado)
    VALUES (NEW.id, NEW.creado_por, 'admin', 'activo');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_grupos_alta_admin
    AFTER INSERT ON grupos_gastos
    FOR EACH ROW EXECUTE FUNCTION grupos_alta_admin_creador();

-- ============================================================
-- SECCIÓN 4: ROW LEVEL SECURITY
-- Habilitar RLS en las 6 tablas nuevas.
-- ============================================================

ALTER TABLE grupos_gastos             ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupo_miembros            ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupo_invitaciones        ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupo_gastos              ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupo_gasto_participantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupo_liquidaciones       ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- SECCIÓN 5: POLÍTICAS RLS POR TABLA
-- ============================================================

-- --- grupos_gastos ---
-- SELECT: solo miembros activos del grupo pueden verlo.
CREATE POLICY "grupos_select" ON grupos_gastos
    FOR SELECT USING (is_group_member(id, auth.uid()));
-- INSERT: el usuario que crea el grupo debe declararse como creador.
CREATE POLICY "grupos_insert" ON grupos_gastos
    FOR INSERT WITH CHECK (auth.uid() = creado_por);
-- UPDATE: solo admins del grupo pueden modificarlo (ej. archivar, renombrar).
CREATE POLICY "grupos_update" ON grupos_gastos
    FOR UPDATE USING (is_group_admin(id, auth.uid()));
-- DELETE: solo admins pueden eliminar (eliminación física, aunque en práctica se archiva).
CREATE POLICY "grupos_delete" ON grupos_gastos
    FOR DELETE USING (is_group_admin(id, auth.uid()));

-- --- grupo_miembros ---
-- SELECT: el propio usuario siempre ve su membresía; miembros activos ven al resto.
CREATE POLICY "miembros_select" ON grupo_miembros
    FOR SELECT USING (
        user_id = auth.uid() OR is_group_member(grupo_id, auth.uid())
    );
-- INSERT: solo admins pueden agregar miembros.
CREATE POLICY "miembros_insert_admin" ON grupo_miembros
    FOR INSERT WITH CHECK (
        is_group_admin(grupo_id, auth.uid())
        OR (auth.uid() = user_id AND is_group_creator(grupo_id, auth.uid()))
    );
-- UPDATE: solo admins pueden cambiar rol o estado (remover miembro = soft update).
CREATE POLICY "miembros_update_admin" ON grupo_miembros
    FOR UPDATE USING (is_group_admin(grupo_id, auth.uid()));
-- DELETE no se usa: bajas son soft (estado='removido').

-- --- grupo_invitaciones ---
-- SELECT para admins: ven todas las invitaciones del grupo.
CREATE POLICY "invitaciones_select_admin" ON grupo_invitaciones
    FOR SELECT USING (is_group_admin(grupo_id, auth.uid()));
-- SELECT para invitado: solo puede ver su propia invitación (por email del JWT).
CREATE POLICY "invitaciones_select_invitado" ON grupo_invitaciones
    FOR SELECT USING (
        LOWER(email_invitado) = LOWER(COALESCE(auth.jwt() ->> 'email', ''))
    );
-- INSERT: solo admins pueden crear invitaciones.
CREATE POLICY "invitaciones_insert_admin" ON grupo_invitaciones
    FOR INSERT WITH CHECK (is_group_admin(grupo_id, auth.uid()));
-- UPDATE: el invitado puede aceptar/rechazar; el admin puede cancelar.
CREATE POLICY "invitaciones_update_invitado" ON grupo_invitaciones
    FOR UPDATE USING (
        LOWER(email_invitado) = LOWER(COALESCE(auth.jwt() ->> 'email', ''))
        OR is_group_admin(grupo_id, auth.uid())
    );

-- --- grupo_gastos ---
-- SELECT: cualquier miembro activo puede ver los gastos del grupo.
CREATE POLICY "gastos_select" ON grupo_gastos
    FOR SELECT USING (is_group_member(grupo_id, auth.uid()));
-- INSERT: miembro activo puede cargar gastos, y debe declararse como creador.
CREATE POLICY "gastos_insert" ON grupo_gastos
    FOR INSERT WITH CHECK (
        is_group_member(grupo_id, auth.uid())
        AND creado_por = auth.uid()
    );
-- UPDATE: el creador o un admin puede modificar/anular (soft delete).
CREATE POLICY "gastos_update" ON grupo_gastos
    FOR UPDATE USING (
        is_group_member(grupo_id, auth.uid())
        AND (creado_por = auth.uid() OR is_group_admin(grupo_id, auth.uid()))
    );
-- DELETE no se usa: anulación es soft (estado='anulado').

-- --- grupo_gasto_participantes ---
-- SELECT: miembro activo del grupo padre puede ver los participantes.
CREATE POLICY "participantes_select" ON grupo_gasto_participantes
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM grupo_gastos g
            WHERE g.id = gasto_id
              AND is_group_member(g.grupo_id, auth.uid())
        )
    );
-- INSERT: solo quien creó el gasto puede asignar participantes.
CREATE POLICY "participantes_insert" ON grupo_gasto_participantes
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM grupo_gastos g
            WHERE g.id = gasto_id
              AND is_group_member(g.grupo_id, auth.uid())
              AND g.creado_por = auth.uid()
        )
    );
-- UPDATE/DELETE: no permitidos directos; se reescriben al anular el gasto (soft).

-- --- grupo_liquidaciones ---
-- SELECT: cualquier miembro activo puede ver las liquidaciones del grupo.
CREATE POLICY "liquidaciones_select" ON grupo_liquidaciones
    FOR SELECT USING (is_group_member(grupo_id, auth.uid()));
-- INSERT: miembro activo puede registrar liquidaciones donde sea parte o sea admin.
CREATE POLICY "liquidaciones_insert" ON grupo_liquidaciones
    FOR INSERT WITH CHECK (
        is_group_member(grupo_id, auth.uid())
        AND registrado_por = auth.uid()
        AND (
            de_user_id = auth.uid()
            OR para_user_id = auth.uid()
            OR is_group_admin(grupo_id, auth.uid())
        )
    );
-- UPDATE: quien la registró o un admin puede anularla (soft delete).
CREATE POLICY "liquidaciones_update" ON grupo_liquidaciones
    FOR UPDATE USING (
        is_group_member(grupo_id, auth.uid())
        AND (registrado_por = auth.uid() OR is_group_admin(grupo_id, auth.uid()))
    );

-- ============================================================
-- SECCIÓN 6: VISTA vw_grupo_saldos
-- Calcula el saldo neto de cada miembro activo por grupo.
-- La lógica JS en el frontend (calcularTransferencias) consume esta vista
-- para generar el mínimo set de transferencias necesarias.
--
-- Fórmula del saldo neto:
--   pagado + liquidado_enviado - asignado - liquidado_recibido
--   positivo = a favor (le deben), negativo = en contra (debe)
-- ============================================================

CREATE OR REPLACE VIEW vw_grupo_saldos AS
WITH pagado AS (
    -- Total que cada usuario pagó en gastos activos del grupo
    SELECT grupo_id, pagado_por AS user_id, COALESCE(SUM(monto), 0) AS total_pagado
    FROM grupo_gastos
    WHERE estado = 'activo'
    GROUP BY grupo_id, pagado_por
),
asignado AS (
    -- Total asignado a cada usuario en gastos activos del grupo
    SELECT g.grupo_id, p.user_id, COALESCE(SUM(p.monto_asignado), 0) AS total_asignado
    FROM grupo_gasto_participantes p
    JOIN grupo_gastos g ON g.id = p.gasto_id
    WHERE g.estado = 'activo'
    GROUP BY g.grupo_id, p.user_id
),
liq_enviado AS (
    -- Total de liquidaciones enviadas (pagos que el usuario realizó a otros)
    SELECT grupo_id, de_user_id AS user_id, COALESCE(SUM(monto), 0) AS total_liquidado_enviado
    FROM grupo_liquidaciones
    WHERE estado = 'confirmada'
    GROUP BY grupo_id, de_user_id
),
liq_recibido AS (
    -- Total de liquidaciones recibidas (pagos que otros le realizaron al usuario)
    SELECT grupo_id, para_user_id AS user_id, COALESCE(SUM(monto), 0) AS total_liquidado_recibido
    FROM grupo_liquidaciones
    WHERE estado = 'confirmada'
    GROUP BY grupo_id, para_user_id
),
miembros AS (
    -- Base: solo miembros activos
    SELECT grupo_id, user_id FROM grupo_miembros WHERE estado = 'activo'
)
SELECT
    m.grupo_id,
    m.user_id,
    COALESCE(p.total_pagado, 0)              AS pagado,
    COALESCE(a.total_asignado, 0)            AS asignado,
    COALESCE(le.total_liquidado_enviado, 0)  AS liquidado_enviado,
    COALESCE(lr.total_liquidado_recibido, 0) AS liquidado_recibido,
    -- Saldo neto: positivo = a favor (le deben), negativo = en contra (debe)
    (
        COALESCE(p.total_pagado, 0)
        - COALESCE(a.total_asignado, 0)
        + COALESCE(le.total_liquidado_enviado, 0)
        - COALESCE(lr.total_liquidado_recibido, 0)
    ) AS saldo_neto
FROM miembros m
LEFT JOIN pagado        p  ON p.grupo_id  = m.grupo_id AND p.user_id  = m.user_id
LEFT JOIN asignado      a  ON a.grupo_id  = m.grupo_id AND a.user_id  = m.user_id
LEFT JOIN liq_enviado   le ON le.grupo_id = m.grupo_id AND le.user_id = m.user_id
LEFT JOIN liq_recibido  lr ON lr.grupo_id = m.grupo_id AND lr.user_id = m.user_id;

-- ============================================================
-- SECCIÓN 7: RPC crear_grupo_gasto_compartido
-- Crea un grupo usando auth.uid() y devuelve el ID nuevo.
-- SECURITY DEFINER evita depender del INSERT directo por PostgREST/RLS.
-- ============================================================

CREATE OR REPLACE FUNCTION crear_grupo_gasto_compartido(
    p_nombre VARCHAR,
    p_descripcion TEXT DEFAULT NULL,
    p_moneda VARCHAR DEFAULT 'ARS'
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_user_id UUID;
    v_grupo_id BIGINT;
BEGIN
    v_user_id := auth.uid();

    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'No autenticado';
    END IF;

    INSERT INTO grupos_gastos (nombre, descripcion, moneda, creado_por)
    VALUES (TRIM(p_nombre), NULLIF(TRIM(COALESCE(p_descripcion, '')), ''), COALESCE(p_moneda, 'ARS'), v_user_id)
    RETURNING id INTO v_grupo_id;

    RETURN v_grupo_id;
END;
$$;

REVOKE ALL ON FUNCTION crear_grupo_gasto_compartido(VARCHAR, TEXT, VARCHAR) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION crear_grupo_gasto_compartido(VARCHAR, TEXT, VARCHAR) TO authenticated;

-- ============================================================
-- SECCIÓN 7: RPC aceptar_invitacion_grupo
-- Operación transaccional: marca invitación como aceptada e inserta
-- al usuario como miembro activo en una sola operación atómica.
-- Idempotente: si el miembro ya existe, reactiva su estado a 'activo'.
-- Invocada por el backend Express con service role después de validar JWT.
-- ============================================================

CREATE OR REPLACE FUNCTION aceptar_invitacion_grupo(p_token UUID, p_user_id UUID)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_grupo_id BIGINT;
BEGIN
    -- Marcar invitación como aceptada (solo si está pendiente).
    -- RETURNING garantiza atomicidad: si no hay fila afectada, v_grupo_id queda NULL.
    UPDATE grupo_invitaciones
       SET estado = 'aceptada', fecha_resolucion = NOW()
     WHERE token = p_token AND estado = 'pendiente'
     RETURNING grupo_id INTO v_grupo_id;

    IF v_grupo_id IS NULL THEN
        RAISE EXCEPTION 'Invitacion invalida o ya resuelta';
    END IF;

    -- Insertar miembro activo. Si ya existía (ej. fue removido y re-invitado),
    -- reactivar sin duplicar la fila (ON CONFLICT DO UPDATE).
    INSERT INTO grupo_miembros (grupo_id, user_id, rol, estado)
    VALUES (v_grupo_id, p_user_id, 'miembro', 'activo')
    ON CONFLICT (grupo_id, user_id) DO UPDATE
        SET estado = 'activo', fecha_baja = NULL;

    RETURN v_grupo_id;
END;
$$;

-- Revocar acceso público; el backend invoca con service role que tiene acceso total.
-- El rol authenticated también necesita ejecutarla (el frontend podría llamarla directamente en fases futuras).
REVOKE ALL ON FUNCTION aceptar_invitacion_grupo(UUID, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION aceptar_invitacion_grupo(UUID, UUID) TO authenticated;

-- ============================================================
-- FIN DE MIGRACIÓN
-- Verificaciones sugeridas post-ejecución:
--   SELECT table_name FROM information_schema.tables
--     WHERE table_schema = 'public'
--     AND table_name IN (
--       'grupos_gastos','grupo_miembros','grupo_invitaciones',
--       'grupo_gastos','grupo_gasto_participantes','grupo_liquidaciones'
--     );
--   SELECT is_group_member(1, auth.uid());  -- debe retornar FALSE sin error
--   SELECT * FROM vw_grupo_saldos LIMIT 1;  -- debe retornar vacío sin error
-- ============================================================

COMMIT;
