-- Migración: Sistema de Ingresos Mensuales
-- Fecha: 2026-05-10
-- Descripción:
--   Convierte la tabla ingresos de un único registro por usuario a
--   múltiples registros mensuales. Agrega campos para descripción,
--   categoría, origen y referencia a ingresos recurrentes.
--   Crea la tabla categorias_ingresos (globales + personales).
--   Crea la tabla ingresos_recurrentes (estructura lista para Fase 2).
--
-- IMPORTANTE: Ejecutar en Supabase > SQL Editor.
-- Preserva datos existentes: el ingreso actual se migra con fecha = hoy.

-- ============================================================
-- PASO 1: Crear tabla categorias_ingresos PRIMERO
-- (debe existir antes de que ingresos pueda referenciarla)
-- ============================================================
CREATE TABLE IF NOT EXISTS categorias_ingresos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre         VARCHAR(100) NOT NULL,
    activa         BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE categorias_ingresos ENABLE ROW LEVEL SECURITY;

-- Solo ve: globales (user_id IS NULL) y las propias
CREATE POLICY "cat_ingresos_select" ON categorias_ingresos
    FOR SELECT USING (user_id IS NULL OR auth.uid() = user_id);

-- Solo puede crear categorías propias
CREATE POLICY "cat_ingresos_insert" ON categorias_ingresos
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Solo puede actualizar las propias
CREATE POLICY "cat_ingresos_update" ON categorias_ingresos
    FOR UPDATE USING (auth.uid() = user_id);

-- Solo puede eliminar las propias
CREATE POLICY "cat_ingresos_delete" ON categorias_ingresos
    FOR DELETE USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_cat_ingresos_user_id ON categorias_ingresos(user_id);

-- ============================================================
-- PASO 2: Insertar categorías globales
-- ============================================================
INSERT INTO categorias_ingresos (user_id, nombre) VALUES
    (NULL, 'Sueldo'),
    (NULL, 'Freelance'),
    (NULL, 'Venta'),
    (NULL, 'Transferencia'),
    (NULL, 'Reintegro'),
    (NULL, 'Otro')
ON CONFLICT DO NOTHING;

-- ============================================================
-- PASO 3: Modificar tabla ingresos
-- ============================================================
-- Eliminar constraint UNIQUE(user_id) para permitir múltiples ingresos por usuario
ALTER TABLE ingresos DROP CONSTRAINT IF EXISTS ingresos_user_id_unique;

-- Agregar columnas nuevas (sin la FK todavía — se agrega como constraint al final)
ALTER TABLE ingresos
    ADD COLUMN IF NOT EXISTS descripcion    TEXT,
    ADD COLUMN IF NOT EXISTS categoria_id  BIGINT,
    ADD COLUMN IF NOT EXISTS origen        VARCHAR(20) NOT NULL DEFAULT 'manual',
    ADD COLUMN IF NOT EXISTS recurrente_id BIGINT,
    ADD COLUMN IF NOT EXISTS fecha_creacion TIMESTAMPTZ DEFAULT NOW();

-- Asegurar que fecha tenga valor en registros migrados
UPDATE ingresos SET fecha = CURRENT_DATE WHERE fecha IS NULL;

-- ============================================================
-- PASO 4: Agregar FK de ingresos → categorias_ingresos
-- ============================================================
ALTER TABLE ingresos
    DROP CONSTRAINT IF EXISTS ingresos_categoria_id_fkey;

ALTER TABLE ingresos
    ADD CONSTRAINT ingresos_categoria_id_fkey
    FOREIGN KEY (categoria_id) REFERENCES categorias_ingresos(id) ON DELETE SET NULL;

-- ============================================================
-- PASO 5: Crear tabla ingresos_recurrentes
-- ============================================================
CREATE TABLE IF NOT EXISTS ingresos_recurrentes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    descripcion         TEXT NOT NULL,
    monto               DECIMAL(12,2) NOT NULL CHECK (monto > 0),
    categoria_id        BIGINT REFERENCES categorias_ingresos(id) ON DELETE SET NULL,
    frecuencia          VARCHAR(20) NOT NULL DEFAULT 'mensual',
    dia_estimado        SMALLINT CHECK (dia_estimado BETWEEN 1 AND 31),
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_inicio        DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin           DATE,
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ingresos_recurrentes_frecuencia_chk CHECK (frecuencia IN ('mensual'))
);

ALTER TABLE ingresos_recurrentes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ingresos_rec_select" ON ingresos_recurrentes
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "ingresos_rec_insert" ON ingresos_recurrentes
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "ingresos_rec_update" ON ingresos_recurrentes
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "ingresos_rec_delete" ON ingresos_recurrentes
    FOR DELETE USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_ingresos_rec_user_id ON ingresos_recurrentes(user_id);
CREATE INDEX IF NOT EXISTS idx_ingresos_rec_activo  ON ingresos_recurrentes(user_id) WHERE activo = TRUE;

-- ============================================================
-- PASO 6: FK de ingresos → ingresos_recurrentes
-- ============================================================
ALTER TABLE ingresos
    ADD CONSTRAINT ingresos_recurrente_id_fkey
    FOREIGN KEY (recurrente_id) REFERENCES ingresos_recurrentes(id) ON DELETE SET NULL;

-- ============================================================
-- PASO 7: Índices en ingresos para consultas por período
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_ingresos_user_fecha ON ingresos(user_id, fecha);

-- ============================================================
-- PASO 8: Restricción de monto positivo en ingresos
-- ============================================================
-- Solo agregar si no existe ya un check en esa columna
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ingresos_monto_positivo' AND conrelid = 'ingresos'::regclass
    ) THEN
        ALTER TABLE ingresos ADD CONSTRAINT ingresos_monto_positivo CHECK (monto > 0);
    END IF;
END $$;

-- ============================================================
-- VERIFICACIÓN (ejecutar por separado para confirmar)
-- ============================================================
-- SELECT COUNT(*) FROM ingresos;
-- SELECT * FROM categorias_ingresos ORDER BY nombre;
-- SELECT column_name, data_type FROM information_schema.columns
--   WHERE table_name = 'ingresos' ORDER BY ordinal_position;
