-- Esquema de Base de Datos para MisGastosApp
-- ============================================

-- Tabla de Categorías
-- Permite clasificar los gastos (reemplaza el uso de cadenas de texto puras)
CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Métodos de Pago
-- Registra cómo se pagó el gasto (Efectivo, Tarjeta, etc.)
CREATE TABLE IF NOT EXISTS metodos_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Gastos
-- Almacena los registros de gastos vinculados a categorías y métodos de pago
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    descripcion TEXT NOT NULL,
    monto DECIMAL(12,2) NOT NULL,
    id_categoria BIGINT NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT,
    id_metodo_pago BIGINT NOT NULL REFERENCES metodos_pago(id) ON DELETE RESTRICT,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    es_fijo BOOLEAN DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Ingresos
-- Cada fila es un ingreso registrado. El dashboard muestra el más reciente (ORDER BY fecha DESC).
-- Migración aplicada: ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS fecha DATE DEFAULT CURRENT_DATE;
CREATE TABLE IF NOT EXISTS ingresos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    monto DECIMAL(12,2) NOT NULL DEFAULT 0,
    fecha DATE DEFAULT CURRENT_DATE,
    fecha_actualizacion TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE metodos_pago ENABLE ROW LEVEL SECURITY;
ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingresos ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso (Categorías y Métodos de Pago son ahora GLOBALES/SISTEMA)
-- Categorías
CREATE POLICY "Allow global select for categories" ON categorias FOR SELECT USING (true);
CREATE POLICY "System only insert categories" ON categorias FOR INSERT WITH CHECK (false);
CREATE POLICY "System only update categories" ON categorias FOR UPDATE USING (false);
CREATE POLICY "System only delete categories" ON categorias FOR DELETE USING (false);

-- Métodos de Pago
CREATE POLICY "Allow global select for payment methods" ON metodos_pago FOR SELECT USING (true);
CREATE POLICY "System only insert payment methods" ON metodos_pago FOR INSERT WITH CHECK (false);
CREATE POLICY "System only update payment methods" ON metodos_pago FOR UPDATE USING (false);
CREATE POLICY "System only delete payment methods" ON metodos_pago FOR DELETE USING (false);

-- Gastos
CREATE POLICY "Users can view their own expenses" ON gastos FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own expenses" ON gastos FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own expenses" ON gastos FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own expenses" ON gastos FOR DELETE USING (auth.uid() = user_id);

-- Ingresos
CREATE POLICY "Users can view their own income" ON ingresos FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own income" ON ingresos FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own income" ON ingresos FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own income" ON ingresos FOR DELETE USING (auth.uid() = user_id);

-- Índices para optimizar consultas comunes
CREATE INDEX idx_gastos_user_id ON gastos(user_id);
CREATE INDEX idx_gastos_fecha ON gastos(fecha);
CREATE INDEX idx_gastos_id_categoria ON gastos(id_categoria);
CREATE INDEX idx_gastos_es_fijo ON gastos(es_fijo);
CREATE INDEX idx_categorias_user_id ON categorias(user_id);
CREATE INDEX idx_metodos_pago_user_id ON metodos_pago(user_id);
CREATE INDEX idx_ingresos_user_id ON ingresos(user_id);

-- ============================================
-- Datos iniciales (Vacío para creación dinámica)
-- ============================================
