-- Esquema de Base de Datos para MisGastosApp
-- ============================================

-- Tabla de Categorías
-- Permite clasificar los gastos (reemplaza el uso de cadenas de texto puras)
CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Métodos de Pago
-- Registra cómo se pagó el gasto (Efectivo, Tarjeta, etc.)
CREATE TABLE IF NOT EXISTS metodos_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Gastos
-- Almacena los registros de gastos vinculados a categorías y métodos de pago
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    descripcion TEXT NOT NULL,
    monto DECIMAL(12,2) NOT NULL,
    id_categoria BIGINT NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT,
    id_metodo_pago BIGINT NOT NULL REFERENCES metodos_pago(id) ON DELETE RESTRICT,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    es_fijo BOOLEAN DEFAULT FALSE,
    huella_digital VARCHAR(64),
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Ingresos
-- Cada fila es un ingreso registrado. El dashboard muestra el más reciente (ORDER BY fecha DESC).
-- Migración aplicada: ALTER TABLE ingresos ADD COLUMN IF NOT EXISTS fecha DATE DEFAULT CURRENT_DATE;
-- Constraint UNIQUE en user_id para garantizar un ingreso por usuario (para upsert idempotente).
CREATE TABLE IF NOT EXISTS ingresos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    monto DECIMAL(12,2) NOT NULL DEFAULT 0,
    fecha DATE DEFAULT CURRENT_DATE,
    fecha_actualizacion TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT ingresos_user_id_unique UNIQUE(user_id)
);

-- Tabla de Perfil de Usuario
-- Almacena preferencias del usuario como el tema seleccionado.
CREATE TABLE IF NOT EXISTS usuarios (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    theme_id VARCHAR(50) DEFAULT 'indigo-light',
    ultima_actualizacion TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE metodos_pago ENABLE ROW LEVEL SECURITY;
ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingresos ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso (Categorías y Métodos de Pago son GLOBALES/SISTEMA — sin user_id, sin restricciones por usuario)
-- Categorías (global — todos ven las mismas)
CREATE POLICY "Allow select categories for all users" ON categorias FOR SELECT USING (true);
CREATE POLICY "Prevent insert categories" ON categorias FOR INSERT WITH CHECK (false);
CREATE POLICY "Prevent update categories" ON categorias FOR UPDATE USING (false);
CREATE POLICY "Prevent delete categories" ON categorias FOR DELETE USING (false);

-- Métodos de Pago (global — todos ven los mismos)
CREATE POLICY "Allow select payment methods for all users" ON metodos_pago FOR SELECT USING (true);
CREATE POLICY "Prevent insert payment methods" ON metodos_pago FOR INSERT WITH CHECK (false);
CREATE POLICY "Prevent update payment methods" ON metodos_pago FOR UPDATE USING (false);
CREATE POLICY "Prevent delete payment methods" ON metodos_pago FOR DELETE USING (false);

-- Gastos
CREATE POLICY "Users can view their own expenses" ON gastos FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own expenses" ON gastos FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own expenses" ON gastos FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own expenses" ON gastos FOR DELETE USING (auth.uid() = user_id);

-- Ingresos
CREATE POLICY "Users can view their own income" ON ingresos FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own income" ON ingresos FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own income" ON ingresos FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own income" ON ingresos FOR DELETE USING (auth.uid() = user_id);

-- Perfil de Usuario
CREATE POLICY "Users can view their own profile" ON usuarios FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON usuarios FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON usuarios FOR UPDATE USING (auth.uid() = id);

-- Índices para optimizar consultas comunes
CREATE INDEX idx_gastos_user_id ON gastos(user_id);
CREATE INDEX idx_gastos_fecha ON gastos(fecha);
CREATE INDEX idx_gastos_id_categoria ON gastos(id_categoria);
CREATE INDEX idx_gastos_es_fijo ON gastos(es_fijo);
CREATE INDEX idx_gastos_huella_digital ON gastos(huella_digital);
CREATE INDEX idx_categorias_user_id ON categorias(user_id);
CREATE INDEX idx_metodos_pago_user_id ON metodos_pago(user_id);
CREATE INDEX idx_ingresos_user_id ON ingresos(user_id);
CREATE INDEX idx_usuarios_id ON usuarios(id);

-- ============================================
-- FASE 1: SISTEMA DE NOTIFICACIONES
-- ============================================

-- Tabla de Notificaciones
-- Almacena todas las notificaciones del usuario con soporte de email.
CREATE TABLE IF NOT EXISTS notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'info',
    -- Tipos válidos: info | success | warning | error
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    origen VARCHAR(30) NOT NULL DEFAULT 'app',
    -- Orígenes válidos: app | gastos | ingresos | n8n | whatsapp | sistema | resumen | proyeccion
    metadata JSONB,
    email_enviado BOOLEAN NOT NULL DEFAULT FALSE,
    email_error TEXT,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Configuración de Notificaciones por Usuario
-- Permite controlar qué notificaciones recibe el usuario y si se envían por email.
CREATE TABLE IF NOT EXISTS configuracion_notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    -- Configuración general de email
    email_habilitado BOOLEAN NOT NULL DEFAULT FALSE,
    email_saldo_bajo BOOLEAN NOT NULL DEFAULT FALSE,
    email_gasto_alto BOOLEAN NOT NULL DEFAULT FALSE,
    email_resumen_diario BOOLEAN NOT NULL DEFAULT FALSE,
    email_resumen_semanal BOOLEAN NOT NULL DEFAULT FALSE,
    email_resumen_mensual BOOLEAN NOT NULL DEFAULT FALSE,
    email_notificaciones_n8n BOOLEAN NOT NULL DEFAULT TRUE,
    -- Configuración de alertas financieras
    notificar_saldo_bajo BOOLEAN NOT NULL DEFAULT TRUE,
    umbral_saldo_bajo DECIMAL(12,2) DEFAULT 5000,
    notificar_porcentaje_ingreso BOOLEAN NOT NULL DEFAULT TRUE,
    porcentaje_maximo_ingreso DECIMAL(5,2) DEFAULT 80,
    notificar_gasto_alto BOOLEAN NOT NULL DEFAULT TRUE,
    monto_gasto_alto DECIMAL(12,2) DEFAULT 10000,
    fecha_actualizacion TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT configuracion_notificaciones_user_id_unique UNIQUE(user_id)
);

-- RLS para notificaciones
ALTER TABLE notificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracion_notificaciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "notificaciones_select" ON notificaciones FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "notificaciones_insert" ON notificaciones FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "notificaciones_update" ON notificaciones FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "notificaciones_delete" ON notificaciones FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "config_notif_select" ON configuracion_notificaciones FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "config_notif_insert" ON configuracion_notificaciones FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "config_notif_update" ON configuracion_notificaciones FOR UPDATE USING (auth.uid() = user_id);

-- Índices para optimizar consultas de notificaciones
CREATE INDEX idx_notificaciones_user_id ON notificaciones(user_id);
CREATE INDEX idx_notificaciones_leida ON notificaciones(user_id, leida);
CREATE INDEX idx_notificaciones_fecha ON notificaciones(user_id, fecha_creacion DESC);
CREATE INDEX idx_config_notif_user_id ON configuracion_notificaciones(user_id);

-- ============================================
-- FASE 4 y 5: ALERTAS AVANZADAS Y RESÚMENES
-- ============================================

-- Nuevas columnas para alertas de gastos fijos/variables (Fase 4)
-- y proyecciones/resúmenes (Fase 5)
ALTER TABLE configuracion_notificaciones
    ADD COLUMN IF NOT EXISTS notificar_gastos_fijos_pendientes  BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notificar_gastos_fijos_exceso      BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS umbral_fijos_ingreso               DECIMAL(5,2) DEFAULT 60,
    ADD COLUMN IF NOT EXISTS notificar_variables_crecimiento    BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS margen_crecimiento_variables       DECIMAL(5,2) DEFAULT 20,
    ADD COLUMN IF NOT EXISTS notificar_concentracion_categoria  BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS porcentaje_concentracion_categoria DECIMAL(5,2) DEFAULT 40,
    ADD COLUMN IF NOT EXISTS email_alertas_gastos_fijos         BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS notificar_proyecciones             BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS objetivo_ahorro_porcentaje         DECIMAL(5,2) DEFAULT 10;

-- ============================================
-- Datos iniciales (Vacío para creación dinámica)
-- ============================================
